// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DoCopyLog() {
  return window['go']['backend']['App']['DoCopyLog']();
}

export function DoFrontendReady() {
  return window['go']['backend']['App']['DoFrontendReady']();
}

export function DoGetFlags() {
  return window['go']['backend']['App']['DoGetFlags']();
}

export function DoGetOS() {
  return window['go']['backend']['App']['DoGetOS']();
}

export function DoGetProcessInfo() {
  return window['go']['backend']['App']['DoGetProcessInfo']();
}

export function DoGetTheme() {
  return window['go']['backend']['App']['DoGetTheme']();
}

export function DoOpenBrowser() {
  return window['go']['backend']['App']['DoOpenBrowser']();
}

export function DoRevealConfig() {
  return window['go']['backend']['App']['DoRevealConfig']();
}

export function DoSetTheme(arg1) {
  return window['go']['backend']['App']['DoSetTheme'](arg1);
}

export function DoStartServer() {
  return window['go']['backend']['App']['DoStartServer']();
}

export function DoStopServer() {
  return window['go']['backend']['App']['DoStopServer']();
}

export function DoVersion() {
  return window['go']['backend']['App']['DoVersion']();
}

export function GetLaunchOptions() {
  return window['go']['backend']['App']['GetLaunchOptions']();
}

export function SetLaunchOptions(arg1) {
  return window['go']['backend']['App']['SetLaunchOptions'](arg1);
}
