// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Pronto() {
  return window['go']['backend']['App']['Pronto']();
}

export function Version() {
  return window['go']['backend']['App']['Version']();
}

export function Write(arg1) {
  return window['go']['backend']['App']['Write'](arg1);
}
