// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendLog(arg1) {
  return window['go']['backend']['App']['AppendLog'](arg1);
}

export function DoCopyLog() {
  return window['go']['backend']['App']['DoCopyLog']();
}

export function DoGetTheme() {
  return window['go']['backend']['App']['DoGetTheme']();
}

export function DoOpenBrowser() {
  return window['go']['backend']['App']['DoOpenBrowser']();
}

export function DoSetTheme(arg1) {
  return window['go']['backend']['App']['DoSetTheme'](arg1);
}

export function DoStartServer() {
  return window['go']['backend']['App']['DoStartServer']();
}

export function DoStopServer() {
  return window['go']['backend']['App']['DoStopServer']();
}

export function DoVersion() {
  return window['go']['backend']['App']['DoVersion']();
}

export function EmitFlags() {
  return window['go']['backend']['App']['EmitFlags']();
}

export function GetLaunchOptions() {
  return window['go']['backend']['App']['GetLaunchOptions']();
}

export function GetOS() {
  return window['go']['backend']['App']['GetOS']();
}

export function GetProcessInfo() {
  return window['go']['backend']['App']['GetProcessInfo']();
}

export function NewWriter(arg1) {
  return window['go']['backend']['App']['NewWriter'](arg1);
}

export function Pronto() {
  return window['go']['backend']['App']['Pronto']();
}

export function SetLaunchOptions(arg1) {
  return window['go']['backend']['App']['SetLaunchOptions'](arg1);
}
