// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Pronto():Promise<void>;

export function Version():Promise<void>;

export function Write(arg1:Array<number>):Promise<number>;
